Looks like a silent bump to '1.19.0-beta1' (#4021)
```
Error: Checksum for Cask 'atom-beta' does not match.

Expected: 6a853f4b5e8734bfd5e4126eec158a36b97639eb7ede7b71538951397e599a86
Actual:   3bb135a1ae6ad10fb8bce9f49a2a7b9a50a3fa9e82c1537fcf44ae0e1b631d08
File:     /Users/benc/Library/Caches/Homebrew/Cask/atom-beta--1.19.0-beta1.zip

To retry an incomplete download, remove the file above.
Error: Install incomplete.
tyr:~/Library/Caches/Homebrew/Cask benc$ brew cask info atom-beta
atom-beta: 1.19.0-beta1
https://atom.io/beta
Not installed
From: https://github.com/caskroom/homebrew-versions/blob/master/Casks/atom-beta.rb
==> Name
Github Atom Beta
```

new sha and checkpoint