Update java-beta to 16,25
Fix a 404 for 16,20 by updating to 16,25 for the java-beta download URL.

```
==> Downloading https://download.java.net/java/early_access/jdk16/20/GPL/openjdk

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java-beta' with message: Download failed: https://download.java.net/java/early_access/jdk16/20/GPL/openjdk-16-ea+20_osx-x64_bin.tar.gz
```